services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: archiver
      POSTGRES_PASSWORD: password
      POSTGRES_DB: archiver
    volumes:
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
    ports:
      - "5432:5432"

  smap:
    build:
      context: .
      dockerfile: Dockerfile
    image: smap:local
    volumes:
      - .:/opt/smap:cached
    working_dir: /opt/smap
    environment:
      PYTHONUNBUFFERED: '1'
      PYTHONPATH: /opt/smap/python
    tty: true
    depends_on:
      - postgres
    ports:
      - "8079:8079"
