services:
  postgres:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: archiver
      POSTGRES_PASSWORD: password
      POSTGRES_DB: archiver
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres-init.sql:/docker-entrypoint-initdb.d/00-hstore.sql:ro
    ports: ["5432:5432"]

  archiver:
    build:
      context: ./hs-archiver
      dockerfile: Dockerfile
    image: smap-archiver:haskell
    depends_on:
      - postgres
    environment:
      DB_CONN: "host=postgres port=5432 user=archiver dbname=archiver password=password"
    ports:
      - "8079:8079"

  smap:
    image: smap:local
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - archiver
    volumes:
      - .:/opt/smap:cached
      - ./docker/example.ini:/etc/smap/example.ini:ro
    working_dir: /opt/smap
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: /opt/smap/python
    ports:
      - "8081:8080"
    command: >
      bash -c "
        sleep 5;
        twistd -n smap /etc/smap/example.ini
      "

volumes:
  pgdata:
